### ISSUE TITLE
Minor correction to license error message

### ISSUE THREAD

**Issue by amueggeATB** [pingidentity/pingctl#22]
https://github.com/pingidentity/pingctl/blob/a0ae124589c77dee38ae86c15bfb5e7d2ecb7236/pingctl#L1018

The second instance of PING_IDENTITY_DEVOPS_USER on this line should be PING_IDENTITY_DEVOPS_KEY .

**Comment by PingDavidR** [comment]
Thanks @amueggeATB - we have a PR to fix this typo now, should be fixed as soon as we get through final steps.  https://github.com/pingidentity/pingctl/pull/25
